Temporary fix to the missing target value error
Traceback (most recent call last):
  File "predict.py", line 150, in <module>
    predictor.predict()
  File "predict.py", line 80, in predict
    for steps, (data, target, filenames) in enumerate(self.dataloader_predict, start=1):
ValueError: not enough values to unpack (expected 3, got 2)